name: emotion-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scikit-learn=1.3.0
  - librosa=0.10.0
  - pysoundfile=0.12.1
  - seaborn
  - pyqt=5
  - pillow=10.0.0
  - ipykernel
  - ipython
  - jupyterlab
  - pip:
      - tensorflow==2.13.0
      - pyqtdarktheme==2.1.0
